services:
  agenda-app:
    build: .
    ports:
      - "8088:8088"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
